# Generated by Django 3.1.4 on 2020-12-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_auto_20201217_0729'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(choices=[('-A', '-A'), ('+A', '+A'), ('-B', '-B'), ('+B', '+B'), ('-AB', '-AB'), ('+AB', '+AB'), ('-O', '-O'), ('+O', '+O')], max_length=10, null=True),
        ),
    ]
