# Generated by Django 3.1.4 on 2020-12-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='health_uid',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
