# Generated by Django 3.1.4 on 2020-12-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0006_patient_health_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cvv',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ex_month',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='ex_year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
