# Generated by Django 3.1.4 on 2020-12-22 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20201221_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='foundation_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nom_beds',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='nom_doctor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='owner_name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
