# Generated by Django 3.1.4 on 2020-12-24 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_patient_card_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='biography',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='days_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='foundation_date',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='days_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nom_beds',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='nom_doctor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='timing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='timing',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Hospital_Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_date', models.DateField(null=True)),
                ('a_timing', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100, null=True)),
                ('p_status', models.CharField(max_length=100, null=True)),
                ('hospital', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.hospital')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='health.patient')),
            ],
        ),
    ]
