# Generated by Django 3.1.4 on 2020-12-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_doctors_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_appointment',
            name='price',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
