# Generated by Django 3.1.4 on 2020-12-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_hospital_appointment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medical',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
